name: WorldEditPlus
main: WorldEditPlus\WorldEditPlus
version: 3.2
api: 5.0.0
author: CreeParker (@cree_parker)
website: https://forum.mcbe.jp/resources/107/
permissions:
  worldeditplus.command.book:
    default: op
  worldeditplus.command.cancel:
    default: op
  worldeditplus.command.clone:
    default: op
  worldeditplus.command.cylinder:
    default: op
  worldeditplus.command.fill:
    default: op
  worldeditplus.command.pos1:
    default: op
  worldeditplus.command.pos2:
    default: op
  worldeditplus.command.sphere:
    default: op
  worldeditplus.command.wand:
    default: op
